[package]
name = "video-sharing-website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-minifier = "3.0.14"
rand = "0.8.4"
